# Generated by Django 3.2.9 on 2021-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.UUIDField()),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('OVA', 'OVA'), ('Special', 'Special'), ('ONA', 'ONA'), ('TV', 'TV')], max_length=7)),
                ('score', models.CharField(default='', max_length=5)),
                ('episodes', models.IntegerField(max_length=4)),
                ('image_url', models.URLField(max_length=255)),
                ('airing', models.BooleanField(default=False)),
                ('synopsis', models.CharField(default='', max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
