# Generated by Django 3.2.9 on 2021-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('title_english', models.CharField(default='', max_length=200)),
                ('title_japanese', models.CharField(default='', max_length=200)),
                ('title_synonyms', models.CharField(default='', max_length=200)),
                ('image_url', models.URLField(default='', max_length=255)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('OVA', 'OVA'), ('Special', 'Special'), ('ONA', 'ONA'), ('TV', 'TV')], default='', max_length=200)),
                ('source', models.CharField(choices=[('Original', 'Original'), ('Manga', 'Manga'), ('Game', 'Game'), ('Unknown', 'Unknown'), ('Web manga', 'Web manga'), ('Light novel', 'Light novel'), ('Other', 'Other'), ('Visual Novel', 'Visual Novel'), ('Music', 'Music')], default='', max_length=200)),
                ('episodes', models.IntegerField(default='0')),
                ('status', models.CharField(choices=[('Finished Airing', 'Finished Airing'), ('Currently Airing', 'Currently Airing'), ('Not yet aired', 'Not yet aired')], default='', max_length=200)),
                ('airing', models.BooleanField(default=False)),
                ('aired_string', models.CharField(default='', max_length=200)),
                ('aired', models.CharField(default='', max_length=200)),
                ('duration', models.CharField(default='', max_length=200)),
                ('rating', models.CharField(default='', max_length=100)),
                ('score', models.CharField(default='', max_length=5)),
                ('scored_by', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('snyopsis', models.CharField(default='', max_length=200)),
                ('premiered', models.CharField(default='', max_length=200)),
                ('broadcast', models.CharField(default='', max_length=200)),
                ('related', models.CharField(default='', max_length=300)),
                ('producer', models.CharField(default='', max_length=200)),
                ('licensor', models.CharField(default='', max_length=200)),
                ('studio', models.CharField(default='', max_length=200)),
                ('genre', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
