# Generated by Django 3.2.9 on 2021-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_id',
        ),
    ]
