# Generated by Django 3.2.9 on 2021-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_anime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
    ]
